package main

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"html/template"
	"log"
	"net/http"
	"os"
	"reflect"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

//go:embed mdi.json
var mdiData []byte

var mdiIcons map[string]string

type TemplateData struct {
	Dashboard
	Config
	Name string
}

type HAState struct {
	EntityID   string `json:"entity_id"`
	Attributes struct {
		FriendlyName string `json:"friendly_name"`
		Icon         string `json:"icon"`
	} `json:"attributes"`
}

func domain(entityID string) string {
	parts := strings.SplitN(entityID, ".", 2)
	if len(parts) < 2 {
		return ""
	}
	return parts[0]
}

func makeOnceFunc() func(string) bool {
	seen := make(map[string]bool)
	return func(key string) bool {
		if seen[key] {
			return false
		}
		seen[key] = true
		return true
	}
}

func makeGlobals(globals map[string]any) func(string) (any, error) {
	return func(key string) (any, error) {
		if val, ok := globals[key]; ok {
			return val, nil
		}
		return nil, fmt.Errorf("Global value '%s' not found", key)
	}
}

func makeTranslate(lang string) func(key string) (string, error) {
	return func(key string) (string, error) {
		return translate(key, lang)
	}
}

func makeDomainTranslations(lang string) func(domain string) (map[string]string, error) {
	return func(domain string) (map[string]string, error) {
		return domainTranslations(domain, lang)
	}
}

func makeUid() func() int {
	uid := 0
	return func() int {
		uid++
		return uid
	}
}

// Maps HA domains to their MDI icon names.
// Generated by claude-sonnet-4-6 based on
// https://github.com/home-assistant/frontend/blob/dev/src/data/icons.ts
// at 2026-05-03.
var domainDefaultIcons = map[string]string{
	"ai_task":                 "star-four-points",
	"air_quality":             "air-filter",
	"alert":                   "alert",
	"automation":              "robot",
	"battery":                 "battery",
	"calendar":                "calendar",
	"climate":                 "thermostat",
	"configurator":            "cog",
	"conversation":            "forum-outline",
	"counter":                 "counter",
	"date":                    "calendar",
	"datetime":                "calendar-clock",
	"device_tracker":          "account",
	"door":                    "door-open",
	"garage_door":             "garage-open",
	"gate":                    "gate",
	"google_assistant":        "google-assistant",
	"group":                   "google-circles-communities",
	"homeassistant":           "home-assistant",
	"homekit":                 "home-automation",
	"humidity":                "water-percent",
	"illuminance":             "brightness-6",
	"image_processing":        "image-filter-frames",
	"image":                   "image",
	"infrared":                "led-on",
	"input_boolean":           "toggle-switch",
	"input_button":            "button-pointer",
	"input_datetime":          "calendar-clock",
	"input_number":            "ray-vertex",
	"input_select":            "format-list-bulleted",
	"input_text":              "form-textbox",
	"lawn_mower":              "robot-mower",
	"light":                   "lightbulb",
	"moisture":                "water",
	"motion":                  "motion-sensor",
	"notify":                  "comment-alert",
	"number":                  "ray-vertex",
	"occupancy":               "home-account",
	"persistent_notification": "bell",
	"person":                  "account",
	"plant":                   "flower",
	"power":                   "flash",
	"proximity":               "apple-safari",
	"radio_frequency":         "video-input-antenna",
	"remote":                  "remote",
	"scene":                   "palette",
	"schedule":                "calendar-clock",
	"script":                  "script-text",
	"select":                  "format-list-bulleted",
	"sensor":                  "eye",
	"siren":                   "bullhorn",
	"stt":                     "microphone-message",
	"sun":                     "white-balance-sunny",
	"temperature":             "thermometer",
	"text":                    "form-textbox",
	"time":                    "clock",
	"timer":                   "timer-outline",
	"template":                "code-braces",
	"todo":                    "clipboard-list",
	"tts":                     "speaker-message",
	"vacuum":                  "robot-vacuum",
	"wake_word":               "chat-sleep",
	"weather":                 "weather-partly-cloudy",
	"window":                  "window-closed",
	"zone":                    "map-marker-radius",
	// domains not in FALLBACK_DOMAIN_ICONS but common enough to include
	"switch":        "toggle-switch-variant",
	"binary_sensor": "circle-outline",
	"media_player":  "cast",
	"fan":           "fan",
	"cover":         "window-shutter",
	"lock":          "lock",
	"camera":        "camera",
	"update":        "package-up",
	"button":        "gesture-tap-button",
}

func friendlyName(raw string, locale string) string {
	raw = strings.ReplaceAll(raw, "_", " ")
	tag := language.Make(locale)
	return cases.Title(tag).String(raw)
}

func applyState(v *reflect.Value, e Entity, state HAState, locale string) {
	if e.Label == "" && state.Attributes.FriendlyName != "" {
		v.FieldByName("Label").SetString(friendlyName(state.Attributes.FriendlyName, locale))
	}
	if e.Icon == "" {
		icon := state.Attributes.Icon
		if icon == "" {
			icon = domainDefaultIcons[domain(e.EntityID)]
		}
		if icon != "" {
			icon = strings.TrimPrefix(icon, "mdi:")
			v.FieldByName("Icon").SetString(icon)
		}
	}
}

func enrichEntities(dashboards map[string]Dashboard, cfg Yaml) (map[string]HAState, error) {
	states := map[string]HAState{}
	err := walkEntities(dashboards, func(f reflect.StructField, v *reflect.Value) error {
		e := v.Interface().(Entity)
		if e.EntityID == "" {
			return nil
		}
		if cached, already := states[e.EntityID]; already {
			applyState(v, e, cached, cfg.Localization.Locale)
			return nil
		}
		state, err := fetchEntityState(e.EntityID, cfg.HA)
		if err != nil {
			return err
		}
		states[e.EntityID] = state
		applyState(v, e, state, cfg.Localization.Locale)
		return nil
	})
	return states, err
}

func fetchEntityState(id string, ha HAConfig) (HAState, error) {
	req, err := http.NewRequest("GET", ha.HTTPURL+"/api/states/"+id, nil)
	if err != nil {
		return HAState{}, err
	}
	req.Header.Set("Authorization", "Bearer "+ha.Token)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return HAState{}, err
	}
	defer resp.Body.Close()
	var state HAState
	if err := json.NewDecoder(resp.Body).Decode(&state); err != nil {
		return HAState{}, err
	}
	return state, nil
}

var funcMap = template.FuncMap{
	"default": func(def any, val any) any {
		if val == nil {
			return def
		}
		v := reflect.ValueOf(val)

		if v.Kind() == reflect.Ptr && v.IsNil() {
			return def
		}
		if v.Kind() == reflect.String && v.String() == "" {
			return def
		}
		if v.Kind() == reflect.Int && v.Int() == 0 {
			return def
		}

		return val
	},
	"mergeDateclock": mergeOverride[map[string]any, Dateclock],
	"bool": func(val *bool) bool {
		if val != nil {
			return *val
		}
		return false
	},
	"css": func(val any) template.CSS {
		return template.CSS(fmt.Sprintf("%v", val))
	},
	"enabledByDefault": func(v *bool) bool {
		if v == nil {
			return true
		}
		return *v
	},
	"disabledByDefault": func(v *bool) bool {
		if v == nil {
			return false
		}
		return *v
	},
	"dict": func(values ...any) map[string]any {
		m := map[string]any{}
		for i := 0; i < len(values); i += 2 {
			key := values[i].(string)
			m[key] = values[i+1]
		}
		return m
	},
	"domainIn": func(entityID string, domains ...string) bool {
		domain := domain(entityID)
		for _, d := range domains {
			if domain == d {
				return true
			}
		}
		return false
	},
	"anyOfIn": func(anyOf []string, in ...string) bool { // O(n) is n^2 but the lists are tiny so its fine
		for _, is := range anyOf {
			for _, of := range in {
				if is == of {
					return true
				}
			}
		}
		return false
	},
	"domain": domain,
	"domains": func(entityIDs []string) []string {
		var out []string
		for _, id := range entityIDs {
			out = append(out, domain(id))
		}
		return out
	},
	"entityIDs": func(entities []Card) []string {
		out := make([]string, len(entities))
		for i, e := range entities {
			out[i] = e.EntityID
		}
		return out
	},
	"icon": func(name string) template.HTML {
		path := mdiIcons[name]
		return template.HTML(fmt.Sprintf(
			`<svg class="icon" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="%s"/></svg>`,
			path,
		))
	},
	"isEmoji": func(s string) bool {
		for _, r := range s {
			return r > 127
		}
		return false
	},
	"json": jsonStr,
	"merge": func(maps ...any) (map[string]any, error) {
		result := map[string]any{}
		for _, m := range maps {
			switch v := m.(type) {
			case map[string]any:
				for k, val := range v {
					result[k] = val
				}
			default:
				rv := reflect.ValueOf(m)
				if rv.Kind() == reflect.Ptr {
					rv = rv.Elem()
				}
				if rv.Kind() != reflect.Struct {
					return nil, fmt.Errorf("merge: unsupported type %T", m)
				}
				rt := rv.Type()
				for i := 0; i < rv.NumField(); i++ {
					f := rt.Field(i)
					if f.IsExported() {
						result[f.Name] = rv.Field(i).Interface()
					}
				}
			}
		}
		return result, nil
	},
	"concat": func(values ...any) string {
		var out strings.Builder
		for _, v := range values {
			out.WriteString(fmt.Sprint(v))
		}
		return out.String()
	},
	"prevScreen": func(d Dashboard, i int) *Screen {
		if i > 0 {
			return &d.Screens[i-1]
		}
		return nil
	},
	"nextScreen": func(d Dashboard, i int) *Screen {
		if i+1 < len(d.Screens) {
			return &d.Screens[i+1]
		}
		return nil
	},
	"once":    nilfunc,
	"globals": nilfunc,
	"uid":     nilfunc,
	"replace": func(old string, new string, s string) string {
		return strings.ReplaceAll(s, old, new)
	},
	"isFull": func(layout string) bool {
		sArr := strings.Split(layout, "-")
		if len(sArr) > 1 {
			return sArr[1] == "full"
		}
		return false
	},
	"translate":          nilfunc,
	"domainTranslations": nilfunc,
	"add": func(vals ...float64) float64 {
		var res float64
		for _, val := range vals {
			res += val
		}
		return res
	},
	"resolveThis": resolveThis,
}

func BuildDash() {
	cfg, err := loadConfig()
	if err != nil {
		log.Printf("Could not load config when building dashboard: %v", err)
		return
	}

	BuildDashFromConfig(cfg)
}

func BuildDashFromConfig(cfg Yaml) {
	themes, err := loadThemes(&cfg)
	if err != nil {
		log.Printf("Could not load themes when building dashboard: %v", err)
		return
	}

	var tmpl *template.Template

	tmpl, err = template.New("").Funcs(funcMap).ParseGlob(frontendPath + "/templates/*.html.tmpl")
	if err != nil {
		log.Printf("Could not return root level templates %v", err)
		return
	}

	tmpl, err = tmpl.ParseGlob(frontendPath + "/templates/css/*.html.tmpl")
	tmpl, err = tmpl.ParseGlob(frontendPath + "/templates/css/*.css.tmpl")
	tmpl, err = tmpl.ParseGlob(frontendPath + "/templates/entities/*.html.tmpl")
	tmpl, err = tmpl.ParseGlob(frontendPath + "/templates/widgets/*.html.tmpl")
	tmpl, err = tmpl.ParseGlob(frontendPath + "/templates/controllers/*.html.tmpl")
	tmpl, err = tmpl.ParseGlob(frontendPath + "/templates/navbar-styles/*.html.tmpl")
	tmpl, err = tmpl.ParseGlob(frontendPath + "/templates/layouts/*.html.tmpl")
	tmpl, err = tmpl.ParseGlob(frontendPath + "/templates/common/*.html.tmpl")
	check(err, "Could not create template object")

	defaultTheme, err := getDefaultTheme()
	check(err, "Could not get default theme")

	type builtDash struct {
		tmpl *template.Template
		data TemplateData
	}

	// First pass, to enrich template data and create function enclosures for each dashboard.
	// Function enclosures break if template (along with its funcmap)
	// is copied after it has been executed
	enrichEntities(cfg.Dashboards, cfg)

	built := make(map[string]builtDash)
	for name, dash := range cfg.Dashboards {
		if isDev {
			log.Printf("=== Preprocessing dashboard '%s' ===\n", name)
		}
		resolvedTheme, err := buildTheme(themes, dash.ThemeRef)
		if err != nil {
			log.Printf("Error reading theme for dashboard %s: %v", name, err)
			return
		}
		dashTheme := Theme{}
		if resolvedTheme != nil {
			dashTheme = *resolvedTheme
		}
		// log.Printf("resolved dash theme is currently: \n%s", jsonStr(dashTheme))
		dashTheme.inheritTheme(defaultTheme)
		// log.Printf("dashTheme inherited the default theme, is now: \n%s", jsonStr(dashTheme))
		dash.Theme = dashTheme

		for i, screen := range dash.Screens {
			resolvedTheme, err := buildTheme(themes, screen.ThemeRef)
			if err != nil {
				log.Printf("Error reading theme at screen[%d] (%s): %v", i, screen.Name, err)
				return
			}
			dash.Screens[i].Theme = resolvedTheme
			usedScreenTheme := resolvedTheme
			if usedScreenTheme == nil {
				usedScreenTheme = &dash.Theme
			} else {
				// Need to inherit vars so we can use variables of parent theme in yaml css fields
				usedScreenTheme.inheritVars(dash.Theme)
			}

			if err := walkAndResolveCSS(&dash.Screens[i], usedScreenTheme.Vars); err != nil {
				log.Printf("Error resolving css fields at screen[%d] (%s): %v", i, screen.Name, err)
			}
		}
		if isDev {
			// log.Printf("Resolved dashboard theme is: %s", jsonStr(dash.Theme))
		}

		funcMap["once"] = makeOnceFunc()

		lang := "en"
		if cfg.Localization.Locale != "" {
			lang = strings.Split(cfg.Localization.Locale, "-")[0]
		}

		globals := map[string]any{
			"Animations": dash.Animations,
			"Lang":       lang,
			"IsDev":      isDev,
		}
		funcMap["globals"] = makeGlobals(globals)

		funcMap["translate"] = makeTranslate(lang)
		funcMap["domainTranslations"] = makeDomainTranslations(lang)
		funcMap["uid"] = makeUid()

		dashTmpl, err := tmpl.Clone()
		if err != nil {
			log.Printf("Could not clone template for %s: %v", name, err)
			continue
		}

		built[name] = builtDash{
			tmpl: dashTmpl.Funcs(funcMap),
			data: TemplateData{dash, cfg.Config, name},
		}

		if isDev {
			log.Print("=== Finished preprocessing ===\n")
		}
	}

	for name, b := range built {
		outputDir := frontendPath + "/static/" + name
		if err := os.MkdirAll(outputDir, 0755); err != nil {
			log.Printf("Could not create output dir for %s: %v", name, err)
			continue
		}
		out, err := os.Create(outputDir + "/index.html")
		if err != nil {
			log.Printf("Could not create output file for %s: %v", name, err)
			continue
		}
		if err := b.tmpl.ExecuteTemplate(out, "main.html.tmpl", b.data); err != nil {
			log.Printf("Could not execute template for %s: %v", name, err)
		}
		out.Sync()
		out.Close()
	}
}
